export const START_SAVE_SORT_ORDER = "START_SAVE_SORT_ORDER";
export const SAVE_SORT_ORDER_SUCCESS = "SAVE_SORT_ORDER_SUCCESS";

export const START_REMOVE_ITEM = "START_REMOVE_ITEM";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_FAILURE = "REMOVE_ITEM_FAILURE";

export const UPDATE_VALUES_START = "UPDATE_VALUES_START";
export const UPDATE_VALUES_SUCCESS = "UPDATE_VALUES_SUCCESS";
export const UPDATE_VALUES_FAILURE = "UPDATE_VALUES_FAILURE";

export const ADD_DUBLICATION_START = "ADD_DUBLICATION_START";
export const ADD_DUBLICATION_SUCCESS = "ADD_DUBLICATION_SUCCESS";
export const ADD_DUBLICATION_FAILURE = "ADD_DUBLICATION_FAILURE";

export const INITIALIZE_DATA = "INITIALIZE_DATA";

export const SAVE_LIST_ORDER_START = "SAVE_LIST_ORDER_START";
export const SAVE_LIST_ORDER_SUCCESS = "SAVE_LIST_ORDER_SUCCESS";
export const SAVE_LIST_ORDER_FAILURE = "SAVE_LIST_ORDER_FAILURE";
